.vscode/settings.json
backend/.gitignore
backend/config/index.ts
backend/constants/index.ts
backend/controller/auth.controller.ts
backend/errors/base.error.ts
backend/errors/client.error.ts
backend/middlewares/error.middleware.ts
backend/repository/user.repository.ts
backend/router/auth.router.ts
backend/server.ts
backend/service/auth.service.ts
backend/utils/index.ts
frontend/client/src/hooks/test.ts
prettier.config.js

[feature/13] 백엔드 폴더 정리

---

frontend/client/jest.config.js
frontend/client/src/App.tsx
frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
frontend/client/src/components/GoodsSection/GoodsSection.tsx
frontend/client/src/index.tsx
frontend/client/src/pages/Main/Main.tsx
frontend/client/tsconfig.json
frontend/client/webpack.common.js

import alias 경로 prefix 변경(`src` =>`@src`)했습니다.
이유는 vscode에서 src로할 경우, auto import가 안되니 생산성이 떨어지는 것 같아 이렇게 수정했습니다. 모두 수정해주세요.

Fix: import path alias (src => @src) 수정

---

README.md

update: 간단한 README 작성

---

.github/workflows/deploy-actions.yaml

deploy workflow의 배포 그룹이름 문제때문에 수정합니다.

[bug-fix] 배포 그룹 이름 수정

---

.github/workflows/deploy-actions.yaml

OAuth 개발 환경에 필요한 추가 환경변수 설정에 대응하기 위한 deploy 스크립트입니다. 
없음

[Deploy] 자동배포 스크립트 수정입니다. OAuth를 위해 필요한 환경변수 추가작업입니다.

---

backend/package-lock.json
backend/package.json
backend/src/config/index.ts
backend/src/database.ts
backend/src/entity/Cart.ts
backend/src/entity/Category.ts
backend/src/entity/DeliveryInfo.ts
backend/src/entity/Goods.ts
backend/src/entity/GoodsImg.ts
backend/src/entity/OrderItem.ts
backend/src/entity/OrderList.ts
backend/src/entity/Payment.ts
backend/src/entity/Promotion.ts
backend/src/entity/User.ts
backend/src/entity/UserAddress.ts
backend/src/entity/Wish.ts
backend/src/repository/category.repository.ts
backend/tsconfig.json

엔티티 리팩토링 및 DB 스네이크 케이스 변경, 카테고리 전체 조회 추가
- OneToMany를 삭제했습니다.
- Entity ! 삭제

[feature/64] 엔티티 리팩토링 및 DB 스네이크 케이스 변경, 카테고리 전체 조회 추가 등

---

frontend/client/src/App.tsx
frontend/client/src/apis/addressAPI.ts
frontend/client/src/pages/MyPage/MyPage.tsx

마이페이지 주소 목록 API 연동 프로토타입
(작업 내역 한줄로 요약)
- (특이 사항 1)

[feature/72] 마이페이지 주소 목록 API 연동 프로토타입

---

frontend/client/src/App.tsx
frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/SearchIcon/SearchIcon.tsx
frontend/client/src/components/Header/HeaderBottom/SearchContainer/SearchContainer.tsx
frontend/client/src/lib/CustomRouter/CustomRouter.tsx
frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx

@Kwongiseok  검색하면 페이지 전환되도록 했습니다. 여기서 이어서 작업해주세요 (자동완성)

Add: Keyword 페이지로  전환

---

frontend/client/src/lib/CustomStyledComponent/index.ts

Custom Styled Component 개선 작업을 진행했습니다.
- `AllHTMLAttributte` 타입을 이용해서 HTML 관련된 모든 속성들을 타입스크립트가 인식할 수 있도록 수정
- CSS Rule 누적 제거

update: styled component 개선

---

backend/src/server.ts

백엔드 express 서버 index.html로의 fallback 추가
- 이상무!

[feature] 백엔드 express 서버 index.html로의 fallback 추가

---

backend/src/controller/cart.controller.ts
backend/src/repository/cart.repository.ts
backend/src/router/cart.router.ts
backend/src/router/index.ts
backend/src/service/cart.service.ts
backend/src/types/request/cart.request.ts
backend/src/types/response/cart.response.ts

Cart API를 작성했습니다.
- 서비스와 레포지토리 단의 페이로드가 조금 타이트하긴 한데, 비즈니스 로직 변경 가능성이 없기 때문에 괜찮을듯합니다!...

[feature/88] Cart API

---

.github/workflows/admin-test-actions.yaml
.github/workflows/deploy-actions.yaml
backend/.gitignore
backend/package-lock.json
backend/src/database.ts
backend/src/server.ts
frontend/admin/jest.config.js
frontend/admin/setUpTests.ts
frontend/admin/src/lib/CustomRouter/CustomRouter.spec.tsx
frontend/admin/src/lib/CustomRouter/CustomRouter.tsx
frontend/admin/src/lib/CustomRouter/index.ts
frontend/admin/src/lib/CustomStyledComponent/CuteomStyledComponent.spec.tsx
frontend/admin/src/lib/CustomStyledComponent/index.ts
frontend/admin/src/pages/Main.tsx
frontend/admin/src/portal/ProductUploadModal/ProductImageUploader/ProductImagePreviews/ProductImagePreviews.tsx
frontend/admin/src/portal/ProductUploadModal/ProductUploadModal.tsx
frontend/admin/webpack.common.js
frontend/admin/webpack.dev.js
frontend/client/src/components/Header/HeaderTop/HeaderTop.tsx

슬슬 Admin 어플리케이션의 작업이 시작될 것 같습니다.
그래서 CI/CD 에 admin 앱을 반영했습니다.

[feature/43] Admin 앱을 CI/CD 적용을 위한 작업

---

.github/workflows/admin-test-actions.yaml
.github/workflows/deploy-actions.yaml

fix: mistyping

---

backend/package-lock.json
backend/package.json
backend/src/server.ts
backend/src/utils/pagination.ts
frontend/client/src/apis/goodsAPI.ts
frontend/client/src/components/GoodsItem/GoodsItem.tsx
frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
frontend/client/src/components/Paginator/Paginator.tsx
frontend/client/src/components/Tag/index.tsx
frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
frontend/client/src/pages/MyPage/MyPageNavBar/NavItem.tsx
frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
frontend/client/src/types/Goods.ts

서버쪽 페이지네이션 로직에 매직넘버로 페이지네이션 limit을 바꿔서 보냈을 때 이상하게 동작하는 부분이 있어서 수정 후 PR 올립니다. 
그리고 클라이언트 앱에서 pagination 관련 리팩토링을 진행했습니다. @kowoohyuk  대부분 우혁님이 작성한 코드를 수정한 내용이라 한번 봐주세요.
마지막으로 로깅을 잘하기 위해 morgan lib 를 추가했습니다.
-  [ ] `morgan` 추가

[BugFix] 상품 페이지 네이션 및 리팩토링 진행했습니다.

---

backend/src/entity/OrderItem.ts
backend/src/repository/order.item.repository.ts
backend/src/repository/order.list.repository.ts
backend/src/service/order.service.ts
backend/src/types/Order.ts
backend/src/types/request/order.request.ts
backend/src/types/response/order.response.ts

Order 생성, 조회 (title, thumbnail 추가)

[feature/102] Order 생성, 조회 (title, thumbnail 추가)

---

backend/src/database.ts
backend/src/repository/order.list.repository.ts
frontend/client/src/apis/orderAPI.ts
frontend/client/src/apis/paymentAPI.ts
frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
frontend/client/src/pages/Order/AfterOrder/AfterOrder.tsx
frontend/client/src/pages/Order/OrderPage.tsx
frontend/client/src/pages/Order/PaymentRadioSelector/PaymentRadioSelector.tsx
frontend/client/src/types/Payment.ts
frontend/client/src/utils/validate.ts

https://user-images.githubusercontent.com/64543699/130012911-cfcb41b2-ef49-416a-921c-ed9bb60f69f9.mov
- 상품 주문 API 일부 수정하였습니다. (req로부터 state를 받지 않고 기본 state를 삽입할 수 있게 변경함)

[feature/120] 주문/결제 페이지 - 주문 API 연동

---

frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/PreviewImage/PreviewImage.tsx
frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
frontend/admin/src/utils/convertGoodsState.ts

제품 등록 시 상태 변환 함수 이용
- (특이 사항 1)
- (특이 사항 2)
- (특이 사항 3)

[feature/127] 제품 등록 시 상태 변환 함수 이용

---

scripts/after_deploy.sh
scripts/before_deploy.sh

배포 테스트 1
code deploy 시 node 가 제대로 가져와지는지 확인하기위한 PR

TEST: Branch 배포 테스트를 위한 PR 

---

frontend/client/src/index.tsx
frontend/client/src/lib/ToastProvider/Toast/Toast.tsx
frontend/client/src/lib/ToastProvider/ToastPortalWrapper/ToastPortalWrapper.tsx
frontend/client/src/lib/ToastProvider/ToastPortalWrapper/ToastProtalWrapper.tsx
frontend/client/src/lib/ToastProvider/ToastProvider.tsx
frontend/client/src/pages/Order/OrderPage.tsx

https://user-images.githubusercontent.com/64543699/130172228-a8db5ce6-583c-4c03-927d-3646632db9e5.mov
usage (in Component):
```js
const pushToast = usePushToast();
const handleClick = () => {
// color, displayTime 생략가능 기본값: 블랙, 3000MS
pushToast({ text: 'hello', color: '#000000', displayTime: 3000 });
};
```

[feature/119] Toast 개발, OrderPage에 적용

---

frontend/client/src/App.tsx
frontend/client/src/pages/Cart/CartPage.tsx
frontend/client/src/pages/MyPage/MyPage.tsx
frontend/client/src/pages/Order/OrderPage.tsx
frontend/client/src/utils/withLoggedIn.tsx

https://user-images.githubusercontent.com/64543699/130306546-119be829-811c-4dde-9e3f-e714a618cf7c.mov

[feature/137] 유효하지 않은 페이지 접근 시, main 페이지로 리다이렉트하는 공용 로직 추가

---

backend/src/controller/goods.controller.ts
backend/src/service/goods.service.ts
frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsDiscountUploader/GoodsDiscountUploader.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsPriceUploader/GoodsPriceUploader.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsStockUploader/GoodsStockUploader.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/UploadContentLeft.tsx
frontend/admin/src/utils/formatToNumber.ts

Create Goods 도중에 오류가 발생해서 예외처리를 수정했습니다.
그리고 Admin App에서 상품 등록 모달에서 숫자타입인 것들은 숫자 input으로 입력받도록 수정했습니다.
@Kwongiseok 
기석님이 작성했던 부분 제가 수정해봤습니다. 한번 봐주세요 input의 입력에 포맷을 적용하는 방식을 다르게 해봤습니다.

[Bug] Controller Component 방식 변경

---

frontend/client/src/lib/ToastProvider/Toast/Toast.tsx
frontend/client/src/lib/ToastProvider/ToastPortalWrapper/ToastPortalWrapper.tsx
frontend/client/src/lib/ToastProvider/ToastProvider.tsx

https://user-images.githubusercontent.com/64543699/130313982-2fb98340-9b94-4f58-b776-4b40388a57a8.mov
usage:
```
pushToast({
text: string;
displayTime?: number;
color?: string;
positionRow?: 'left' | 'center' | 'right';
positionColumn?: 'top' | 'bottom';
})
```

[feature/146] Toast 개선

---

frontend/client/src/components/AddressCard/AddressCard.tsx
frontend/client/src/components/AddressModals/AddressForm/AddressForm.tsx
frontend/client/src/components/AddressModals/AddressFormCore/AddressFormCore.tsx
frontend/client/src/components/AddressModals/AddressManageModal/AddressSelectPage/AddressSelectPage.tsx
frontend/client/src/components/AddressModals/Loading/Loading.tsx
frontend/client/src/components/AddressModals/Modal/Modal.tsx
frontend/client/src/pages/Cart/CartPage.tsx
frontend/client/src/pages/Order/AfterOrder/AfterOrder.tsx
frontend/client/src/pages/Order/OrderPage.tsx
frontend/client/src/utils/composeComponent.ts
frontend/client/src/utils/withScrollToTopOnMount.tsx

https://user-images.githubusercontent.com/64543699/130381943-d91c2da8-9513-4834-a282-676c60b863a7.mov
- 페이지 전환 시 스크롤 상태가 유지되는 문제 해결하기위해 고차함수를 도입하였습니다.
- 일련의 고차함수 조합을 ~~용이~~ 이용하기 위해 compose 함수를 작성하였습니다.
- 배송지 폼에 벨리데이션에 필요한 정보를 저장하는 위치에 대해서 고민해볼 필요가 있는 듯합니다.

[feature/152] client UX 개선 시도

---

backend/src/entity/Review.ts
backend/src/entity/ReviewImg.ts

[feature/188] 리뷰 entity 추가

---

frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
frontend/client/src/components/ReviewForm/ReviewForm.tsx
frontend/client/src/components/ReviewForm/ReviewFormContents/ReviewFormContents.tsx
frontend/client/src/components/ReviewForm/ReviewFormFooter/ReviewFormFooter.tsx
frontend/client/src/components/ReviewForm/ReviewFormHeader/ReviewFormHeader.tsx
frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewFormImage.tsx
frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageList/ReviewFormPreviewImage/ReviewFormPreviewImage.tsx
frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageList/ReviewImageList.tsx
frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageUploadButton/ReviewImageUploadButton.tsx
frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewFormRate.tsx
frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewRate/RateStar/RateStar.tsx
frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewRate/ReviewRate.tsx
frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
frontend/client/src/portal/ReviewFormModal/ReviewFormModal.tsx

review 작성 Form (이미지 업로드, Contents, 별점) 컴포넌트
https://user-images.githubusercontent.com/18898526/130626459-76d4b4de-106f-404b-97d2-616ba8d13d2e.mov

[feature/187] review 작성 Form (이미지 업로드, Contents, 별점) 컴포넌트

---

backend/src/constants/database.error.name.ts
backend/src/controller/review.controller.ts
backend/src/database.ts
backend/src/entity/ReviewImg.ts
backend/src/repository/review.repository.ts
backend/src/router/index.ts
backend/src/router/review.router.ts
backend/src/service/goods.service.ts
backend/src/service/review.service.ts
backend/src/types/request/review.request.ts
frontend/client/src/apis/reviewAPI.ts
frontend/client/src/components/ReviewForm/ReviewForm.tsx
frontend/client/src/components/ReviewForm/ReviewFormFooter/ReviewFormFooter.tsx
frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewFormImage.tsx
frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
frontend/client/src/portal/ReviewFormModal/ReviewFormModal.tsx
frontend/client/src/types/Review.ts

Review 생성, 수정 API 작성 [FE] Review 생성, 수정 API 연동
[FE]
[BE]
프론트엔드에서 API를 통해 체크만해봤습니다
어진님이 만들어놓으신 리뷰리스트와 병합해서 완전한 클라이언트 연동을 진행할 예정입니다.
백엔드 로직만 봐주셔도 될 듯 합니다! :)

[feature/194] Review 생성, 수정 API 작성 [FE] Review 생성, 수정 API 연동

---

frontend/client/webpack.prod.js

Git Action 에서 번들링이 블락 되버리는 현상 원인 제거

fix:bundle error 제거

---

backend/src/controller/review.controller.ts
backend/src/entity/Review.ts
backend/src/repository/review.repository.ts
backend/src/router/review.router.ts
backend/src/service/review.service.ts
backend/src/types/Review.ts
frontend/client/src/apis/reviewAPI.ts
frontend/client/src/components/ReviewContainer/ReviewContainer.tsx
frontend/client/src/components/ReviewContainer/ReviewContainerHeader/ReviewContainerHeader.tsx
frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx

https://user-images.githubusercontent.com/64543699/130795015-7d9d7087-02bb-48f2-bf26-7b3bc59da7a9.mov

[feature/213] 상품상세페이지 리뷰 컨테이너 마무리

---

backend/src/repository/review.repository.ts

spread 연산자를 Object.assign()으로 변환하는 과정에서 생긴 오류를 수정하였습니다.

[fix] review 레포지토리 오류

---

backend/src/service/category.service.ts
frontend/admin/src/components/CloseButton/CloseButton.tsx
frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
frontend/admin/src/pages/Main/Main.tsx
frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategory/TopSellingCategory.tsx
frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategoryList.tsx
frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoods/TopSellingGoods.tsx
frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoodsList.tsx
frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
frontend/admin/src/portal/OrderModal/OrderCard.tsx
frontend/admin/src/portal/OrderModal/OrderGoods.tsx
frontend/admin/src/portal/OrderModal/OrderModal.tsx
frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
frontend/client/src/pages/Main/Main.tsx

Admin Page 대시보드 Design 개선작업을 진행했습니다.

[feature] 대시보드 디자인 개선 작업 진행 및 Promotion dot 사라지는 버그 수정

---

backend/src/config/index.ts
backend/src/constants/index.ts
backend/src/controller/category.controller.ts
backend/src/controller/goods.controller.ts
backend/src/database.ts
backend/src/repository/category.repository.ts
backend/src/repository/goods.img.repository.ts
backend/src/repository/goods.repository.ts
backend/src/repository/user.repository.ts
backend/src/repository/wish.repository.ts
backend/src/router/category.router.ts
backend/src/service/auth.service.ts
backend/src/service/cart.service.ts
backend/src/service/category.service.ts
backend/src/service/goods.service.ts
backend/src/service/order.service.ts
backend/src/service/promotion.service.ts
backend/src/service/review.service.ts
backend/src/service/wish.service.ts
frontend/admin/src/apis/categoryAPI.ts
frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsCategoryUploader/GoodsCategoryUploader.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsStateUploader/GoodsStateUploader.tsx
frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/UploadContentRight.tsx
frontend/admin/src/types/Category.ts
frontend/admin/src/types/Goods.ts
frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx

이슈에서 제보된 상품관련 버그 수정
- #250 에서 제보된 상품관련 버그 등 상품관련 버그를 수정하였습니다. :)

[feature/250] 이슈에서 제보된 상품관련 버그 수정 (내용 참고!)

---

backend/src/controller/goods.controller.ts
backend/src/types/request/goods.request.ts
backend/src/utils/convertStringBooleanToBoolean.ts
frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx

불필요한 JSON.parse, stringify 삭제
```
isGreen: Boolean(String(isGreen) === '1')
```
```
const { title, isGreen, stock, state, price, discountRate, category, deliveryInfo } = JSON.parse(JSON.stringify(req.body));
```
```
isGreen : convertStringBooleanToBoolean(isGreen)
```
- JSON.parse와 JSON.stringfy는 필요없는 과정이었네요! 지호님 감사합니다 :)

불필요한 JSON.parse, stringify 삭제 및 유틸함수 추가

---

backend/src/service/user.address.service.ts
frontend/client/src/components/AddressModals/AddressFormCore/AddressFormCore.tsx

https://user-images.githubusercontent.com/64543699/131300628-b7cc8ca5-5da8-4a0c-a72c-8ad85b67c0a6.mov

[feature/253] 우편번호 validation 추가
