woowa-techcamp-2021/store-5

- frontend/client/public/index.html
- frontend/client/src/App.tsx
- frontend/client/src/portal/TestModal/TestModal.tsx
- frontend/client/src/portal/portal.tsx
화면에 그려지는 root 외에 같은 depth의 id = portal 을 가지는 <div>에 그려주는 역할을 하는 것이 portal입니다.
portal을 이용해서 modal을 구현한 예제 코드를 첨가하였습니다.
portal로 감싸주면,  감싸진 해당 컴포넌트는 portal 아래에서 그려지는 구조입니다.
[portal 공식문서](https://ko.reactjs.org/docs/portals.html)
> [feature/15] portal 예시코드

- .github/workflows/client-test-actions.yaml
CI(Continuous Integration)을 위해 Client App 의 jest 테스트를 통과하는 Git Action을 추가했습니다.
린트관련해서도 gitaction을 만들면 좋을 듯 합니다.
- 아마 gitaction은 추후 CI/CD를 위해 미리 공부를 해두는게 좋을 듯합니다.
> [feature/23] Client App Jest 테스트 검사를 위한  git action 스크립트 추가

- .github/workflows/client-test-actions.yaml
이전 Git Action `client-test-actions.yaml` 은 push 할 때마다 git action이 수행되었지만 `dev`, `main` 브랜치로 PR을 날리거나 Push를 했을 때 수행 되도록 재 수정 했습니다.
거의 1분이 걸리는데 `npm install`은 캐싱하는 방법을 찾아봐야할 것 같습니다.
결과는 스크린샷으로 남기겠습니다.
PR 을 올렸을 때 검사가 제대로 되는지
통과했을 때때
> [feature/23] Git Action event trigger 조건 수정

- backend/src/config/index.ts
- backend/src/entity/User.ts
User 엔티티 수정 및 TypeORM 동기화 설정 추가했습니다!
User 엔티티는 githubId와 date 관련 컬럼만 Not null입니다.
100자 제한으로 email도 추가했으며, githubId도 100자 제한을 했는데 깃허브에서 회원가입시 100글자까지 유효성 검사를 통과하고 있어서 그렇게 설정했습니다 :)
> [feature/18] User 엔티티 수정

- frontend/client/package.json
- frontend/client/src/components/Footer/Footer.tsx
- frontend/client/src/components/GoodsItem/GoodsItem.tsx
- frontend/client/src/components/Tag/index.tsx
- frontend/client/src/pages/Main/Main.tsx
- frontend/client/src/pages/Main/SideBar/SideBar.spec.tsx
- frontend/client/src/pages/Main/SideBar/SideBar.tsx
메인 화면에서 상품 이미지 호버효과와 최근 상품리스트를 보여주는 사이드바를 구현했습니다. (+ 푸터)
- 디자인적으로 개선할만한 내용들을 더 추가해볼만합니다. 추후에 UI/UX 관련해서 주말에 피그마 작업을 조금 해볼까합니다.
- Sidebar도 intersection observer를 적용해볼만합니다. 기석님 코드가 머지되면 참고해서 적용해보겠습니다.
> [feature/9] 상품 이미지 호버 효과와 최근상품리스트를 보여주는 사이드바 구현

- backend/src/controller/category.controller.ts
- backend/src/database.ts
- backend/src/repository/category.repository.ts
- backend/src/router/category.router.ts
- backend/src/router/index.ts
- backend/src/service/category.service.ts
- backend/src/types/response/category.response.ts
- frontend/client/src/apis/base.ts
- frontend/client/src/apis/categoryAPI.ts
- frontend/client/src/components/Header/HeaderBottom/Category/Category.tsx
- frontend/client/src/components/Header/HeaderBottom/Category/SubCategoryList/SubCategoryList.spec.tsx
- frontend/client/src/components/Header/HeaderBottom/Category/SubCategoryList/SubCategoryList.tsx
- frontend/client/src/types/Category.ts
카테고리 조회하는 API를 만들었습니다. 
> Repository는 DB에 있는 데이터를 돌려주는 용도로 역할을 최소화 시키는 게 좋을 듯합니다.
저는 service 계층에서 repository에서 받은 데이터를 이용해서 category 계층 구조로 데이터 변환작업을 진행했습니다. 다른 분들도 이렇게하는것이 어떨까 생각이 듭니다. repository는 typeorm 문법만 남겨두려고 노력해야할 듯합니다.
그리고 TypeORM `create`, `save` 와같은 API들을 정확히 알고 쓰는게 중요할듯합니다. 공식문서를 꼭 참조해주세요
- 포스트맨으로 확인한 응답데이터 형태
- Header 컴포넌트와 API 연동
- `database.ts` 여기에 초기 데이터를 넣어두는 작업을 추가하는데 너무 커지지않게 추후에 파일로 따로 분리하면 좋을듯하네요
> [feature/77] Category API 구현

- backend/src/controller/wish.controller.ts
- backend/src/entity/Wish.ts
- backend/src/repository/wish.repository.ts
- backend/src/router/index.ts
- backend/src/router/wish.router.ts
- backend/src/service/wish.service.ts
- backend/src/types/response/wish.response.ts
(작업 내역 한줄로 요약)
찜하기 등록
- Wish 삭제는 정상 처리시 별다른 데이터를 반환하지 않고 있습니다.  
초안에 없어서 그렇게 해뒀는데 이 부분에 대해서 내일 함께 얘기해보면 어떨까요? 😄 
- 클라이언트 연동과 함께 더미 데이터를 작업하려 합니다.  
- 상품 목록 연동 진행후 작업 재개 하도록 하겠습니다.
> [feature/80] 찜하기 API 1/2 (클라이언트 미연동)

- backend/src/controller/payment.controller.ts
- backend/src/controller/promotion.controller.ts
- backend/src/database.ts
- backend/src/entity/Promotion.ts
- backend/src/repository/promotion.repository.ts
- backend/src/router/index.ts
- backend/src/router/promotion.router.ts
- backend/src/service/promotion.service.ts
- backend/src/types/request/promotion.request.ts
- backend/src/types/response/promotion.response.ts
- frontend/client/src/apis/promotionAPI.ts
- frontend/client/src/pages/Main/Main.tsx
Promotion 관련 API 를 구현했습니다. (추가/조회) 
이미지 업로드관련해서는 기석님이 진행하시는 Goods 업로드 API가 완료되면 같이 반영해보겠습니다. 
그리고 클라이언트에 연동해놨습니다.
- 프로모션 생성시 `goodsId`는 우선 안넣어놨습니다. 상품 API 등록이 완료됐을 시점에 넣겠습니다.
> [feature/84] Promotion API 구현 및 클라이언트와 연동

- appspec.yml
- scripts/after_deploy.sh
- scripts/before_deploy.sh
히스토리 : admin app 을 배포하던 중 임시로 image 업로드 기능을 테스트하기 위해 backend uploads 폴더를 express multer가 추가해주도록 하는 기능을 추가했습니다.  그런데 배포 스크립트를 실행하는 권한때문에 해당 폴더를 생성할 수 없는 상황
해결 : 배포시 권한 수정
> fix: uploads 폴더 생성 권한 허용하도록 code agent permission 변경

- scripts/after_deploy.sh
- scripts/before_deploy.sh
Code Deploy 를 이용해서 배포할 경우, PM2가 계속 실행되지않는 현상이 있어서 확인해보니 npm의 경로를 결정하는 코드가 .bashrc에 있어서 그랬습니다. 스크립트를 수정했습니다.
> fix: 배포 스크립트 pm2 못찾는 에러 해결

- frontend/client/src/hooks/usePushToOrderPage.ts
- frontend/client/src/pages/Cart/CartPage.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
- frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
- frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsList.tsx
- frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsListItem/OrderGoodsListItem.tsx
- frontend/client/src/pages/Order/OrderPage.tsx
- frontend/client/src/recoil/orderState.ts
- frontend/client/src/types/Goods.ts
https://user-images.githubusercontent.com/64543699/129866130-33e75132-626c-41d6-9741-8d92a84b84be.mov
- 상품 디테일 페이지 내부 컴포넌트의 코드가 일부 수정되었습니다. (@kowoohyuk )
- 훅을 사용해서 주문/결제 페이지로 상품을 전달하며 이동하도록 구현하였습니다.
> [feature/103] Recoil을 사용해 주문/결제 페이지로 상품을 전달하기

- backend/src/controller/goods.controller.ts
- backend/src/middlewares/set-authenticate.middleware.ts
- backend/src/router/goods.router.ts
- backend/src/service/goods.service.ts
- frontend/client/src/components/GoodsItem/GoodsItem.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
- frontend/client/src/portal/CartModal/CartForm/CartForm.tsx
상품 상세 및 상품 컴포넌트 API 연동
- 회원, 비회원 모두 접근할 수 있는 요청을 위해 setAuthenticate 함수를 추가했습니다.
- 클라이언트 에러 처리는 토스트 팝업 적용 이후 처리하도록 하겠습니다. :)
- 이제 어드민 상품 관리 페이지 시작!
> [feature/94] 상품 상세 및 상품 컴포넌트 API 연동

- .github/workflows/deploy-actions.yaml
- scripts/after_deploy.sh
- scripts/before_deploy.sh
AWS EC2(small) 인스턴스에 배포를 하는 git action(`Build & Deploy`) 배포 과정에서 node_module도 함께 배포가 되고 있습니다.
문제는 AWS EC2 에 Code Agent가 default 설정으로 revision(이전 배포파일)을 5개까지 유지하고 있었고 5개 버젼의 배포 파일들을 서버가 가지고 있을 경우,  저희 EC2 저장용량(8GB)를 넘게 되어서 현재는 이전 버젼의 배포파일을 1개까지만 유지하도록 설정을 변경했습니다.
하지만 node_module자체는 번들링이된 상태에서는 쓸모가 없기 때문에 제거해줘도 좋을 것 같은 판단으로 git action 에서 node_modules 디렉토리를 지워주는 스크립트를 추가했습니다.
그리고 현재 이미지를 S3가 아닌 서버 폴더에 저장하는 형태라 언제 서버가 다운될 지 모르는 상황이라 최대한 줄여보고 서둘러 `S3-Multer`를 적용하는 방법을 찾아봐야할 것 같습니다.
- 현재 기준으로  2개의 배포 Revision을 들고 있는 서버 용량 (대략 1GB 정도)
> [Deploy] 배포 파이프라인 에서 node_module 제거해서 번들링 결과만 배포

- scripts/after_deploy.sh
- scripts/before_deploy.sh
배포시 지속적으로 PM2가 실행되지않는걸 확인해보니 Code Deploy의 Hook을 통해 스크립트를 실행시 node경로는 제대로 못찾는 것을 확인하고 .bash_rc에서 nvm을 통해 node 경로를 찾는 코드를 배포 훅 스크립트 시작부분에 추가했습니다.
먼길을 돌아온느낌입니다. 이제진짜 자동 배포입니다.
> [Bug] deploy 시 node 를 못 찾는 문제 해결.

- backend/src/controller/order.controller.ts
- backend/src/database.ts
- backend/src/entity/OrderItem.ts
- backend/src/entity/OrderList.ts
- backend/src/repository/order.item.repository.ts
- backend/src/repository/order.list.repository.ts
- backend/src/router/order.router.ts
- backend/src/service/goods.service.ts
- backend/src/service/order.service.ts
- backend/src/types/Order.ts
- backend/src/types/Pagination.ts
- backend/src/types/response/order.response.ts
- backend/src/utils/pagination.ts
- frontend/client/src/apis/orderAPI.ts
- frontend/client/src/components/Header/Header.tsx
- frontend/client/src/pages/GoodsDetail/RelationSection/RelationSection.tsx
- frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
- frontend/client/src/pages/MyPage/MyOrderListView/MyOrderListView.tsx
- frontend/client/src/pages/MyPage/MyOrderListView/OrderCard.tsx
- frontend/client/src/pages/MyPage/MyPage.tsx
- frontend/client/src/pages/MyPage/MyPageNavBar/MyPageNavBar.tsx
- frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
- frontend/client/src/types/Order.ts
- frontend/client/src/utils/dateHelper.ts
- frontend/client/src/utils/numberHelper.ts
주문 조회 관련 API 가 있었지만 Pagination이 안되서 새로 Pagination을 구성했습니다. 기존의 OrderList API 를 제거해야할지 용도가 있을지 같이 이야기해보고 결정하겠습니다.
주문조조회관련 기능을 간단히 리스트만 만들었습니다. Order에서 OrderItem을 자세히보려면 모달이 필요할 듯합니다. 모달은 다른 PR로 올리도록하겠습니다.
- Pagination API를 개발하면서 느낀점이지만 각 API에 맞는 Pagination Props를 일일히 만들 필요는 없을 것 같습니다.
Pagination을 위한 속성들(limit, offset)은 항상정해져 있으니 나머지는 다른 값들(userId, category ...) 은 argument로 받으면 될 듯합니다.
> [feature/104] 주문 조회 Pagination API 추가 후 Client App 과 연동

- backend/src/database.ts
- backend/src/entity/Order.ts
- backend/src/entity/OrderItem.ts
- backend/src/entity/User.ts
- backend/src/repository/order.item.repository.ts
- backend/src/repository/order.list.repository.ts
- backend/src/service/order.service.ts
- backend/src/types/response/order.response.ts
- frontend/client/src/pages/MyPage/MyOrderListView/MyOrderListView.tsx
- frontend/client/src/pages/MyPage/MyOrderListView/OrderCard.tsx
- frontend/client/src/pages/MyPage/MyOrderListView/OrderItemCard.tsx
- frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
- frontend/client/src/types/Order.ts
Order 관련 API들을 리팩토링(OrderList 를 Order로 엔티티 이름을 수정했습니다.)  모두 데이터베이스를 한번 비워야할 듯합니다. 이미 데이터가 있다면 마이그레이션을 자동으로 할 수 없습니다. (테이블 이름이 바뀌어서 제약조건변경이 필요)
MyPage 주문 내역에서 OrderItem들 보여주도록 수정.
- Entity의 참조 컬럼들의 `@ManyToOne`의 설정을 제대로하고 있는지 체크해봐야할 듯합니다.
예를 들어 아래의 Goods Entity의 `(deliveryInfo) => deliveryInfo.id` 설정을 마다 deliveryInfo.goodsList 이런식으로 나타내거나
deliveryInfo에서 Goods관련 관계가 필요없는 경우, 제거하는게 맞아보입니다. 해당 설정의 정확한 효력은 문서를 더 찾아봐야할 듯합니다.
> [feature/142] 마이페이지 주문리스트 기능 확장 및 리팩토링 (관련 OrderItem 확장해서 보여주기)

- backend/src/controller/category.controller.ts
- backend/src/controller/goods.controller.ts
- backend/src/repository/category.repository.ts
- backend/src/repository/goods.repository.ts
- backend/src/router/category.router.ts
- backend/src/router/goods.router.ts
- backend/src/service/category.service.ts
- backend/src/service/goods.service.ts
- backend/src/types/response/category.response.ts
- frontend/admin/package-lock.json
- frontend/admin/package.json
- frontend/admin/src/App.tsx
- frontend/admin/src/apis/categoryAPI.ts
- frontend/admin/src/apis/goodsAPI.ts
- frontend/admin/src/pages/Main/CategoryPieChart/CategoryPieChart.tsx
- frontend/admin/src/pages/Main/Main.tsx
- frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoods/TopSellingGoods.tsx
- frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoodsList.tsx
- frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsCategoryUploader/GoodsCategoryUploader.tsx
- frontend/admin/src/theme/theme.ts
- frontend/admin/src/types/Chart.ts
- frontend/admin/src/utils/convertCountOfSell.ts
- frontend/client/src/components/GoodsItem/GoodsItem.tsx
- frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
- frontend/client/src/pages/Main/Main.tsx
대시보드- 상품 카테고리 비율 차트, TOP 상품 컴포넌트 개발 
클라이언트 (로그인,로그아웃 메인 UX 개선)
https://user-images.githubusercontent.com/18898526/130407138-f0f93911-5b9a-4166-a782-09513ea4ab84.mov
https://user-images.githubusercontent.com/18898526/130407208-36bfd2ce-56e5-45ae-bf61-650e879da603.mov
- isWish가 props로 주어짐에도 불구하고, useState로 wish를 따로 상태관리하고 있어서 rendering이 되지 않는 점을 해결하기 위해
useEffect에서 isWish 값에 따라 다시 렌더링이 될 수 있도록 로직을 추가했습니다
- 차트 애니메이션의 경우 오른쪽 탑 5 상품이 렌더링 되는 속도와 차이가 나다보니 너무 어색해서 아래 Component들이 구현되고나서 애니메이션을 구상해봐야할 것 같습니다.
> [feature/151] 대시보드- 상품 카테고리 비율 차트, TOP 상품 컴포넌트 개발 (Client-로그인,로그아웃 메인 UX 개선)

- backend/src/controller/promotion.controller.ts
- backend/src/entity/Promotion.ts
- backend/src/repository/promotion.repository.ts
- backend/src/router/promotion.router.ts
- backend/src/service/promotion.service.ts
- frontend/client/src/apis/promotionAPI.ts
- frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
- frontend/client/src/pages/Main/Main.tsx
프로모션 조회수 API 구현 및 클라이언트 연동
- slick 클릭 이벤트 z-index 이슈를 css 클래스 선택자로 해결했습니다.
> [feature/118] 프로모션 조회수 API 구현 및 클라이언트 연동

- frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/IconContainerStyle.ts
- frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/ShoppigCartIcon/ShoppingCartIcon.tsx
- frontend/client/src/pages/Cart/CartPage.tsx
- frontend/client/src/recoil/cartState.ts
https://user-images.githubusercontent.com/64543699/130531664-7aaa5217-a770-4030-bca9-9124b50c37b7.mov
- 헤더와 장바구니 페이지의 데이터 일관성을 맞추기 위해 장바구니 상태를 리코일로 관리하게 하였습니다.
> [feature/173] Client Header에서 장바구니 개수를 렌더링

- backend/src/repository/order.list.repository.ts
- frontend/admin/src/App.tsx
- frontend/admin/src/apis/orderAPI.ts
- frontend/admin/src/hooks/useInterval.ts
- frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
- frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
- frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
- frontend/admin/src/pages/Main/Main.tsx
- frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTable.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderRow.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableBody.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableHead.tsx
- frontend/admin/src/types/Goods.ts
- frontend/admin/src/types/Order.ts
- frontend/admin/src/utils/dateHelper.ts
- frontend/admin/webpack.common.js
- frontend/admin/webpack.dev.js
- frontend/client/src/components/SideBar/RecentGoodsView.tsx
- frontend/client/src/hooks/useRecentGoodsHistory.ts
- frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
- frontend/client/src/pages/MyPage/MyOrderListView/MyOrderListView.tsx
- frontend/client/src/pages/MyPage/MyProfileView/MyProfileView.tsx
- frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
- frontend/client/src/recoil/recentGoodsState.ts
- frontend/client/webpack.common.js
- frontend/client/webpack.dev.js
주문관련 API를 활용해서 실시간 주문 현황과 모든 주문 조회 탭을 만들었습니다.
기술적으로 특별한 내용은 없습니다. 주문을 보여주는 박스에서  어떤 데이터를 보여줘야하는지를 등등을 회의를 통해 다시 결정해야할 것 같습니다.
- 현시점에서 대시보드의 디자인에 대해 다같이 의논해봐야할 것 같습니다.
> [feature/] 관리자 페이지 주문 조회 화면 개발 및 대시보드 속 실시간 주문 현황 컴포넌트 개발 

- backend/src/controller/order.controller.ts
- backend/src/repository/order.list.repository.ts
- backend/src/router/order.router.ts
- backend/src/service/order.service.ts
- frontend/admin/package.json
- frontend/admin/src/apis/orderAPI.ts
- frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
- frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
- frontend/admin/webpack.common.js
- frontend/admin/webpack.dev.js
- frontend/client/src/apis/orderAPI.ts
긴급으로 수정내용 반영하고자합니다. 
- 관리자 페이지에서 사용할 Order API 추가 (관리자페이지에서 권한이 적용되는 API를 사용하지않고 새로운 API 생성)
- 번들링 후 배포시 발생하는 버그 제거.  (webpack publicPath를 잘못 지정해서 발생)
> [HotFix] Webpack History Fallback 수정 및 admin 에서  사용할  Order API 추가

- backend/src/controller/category.controller.ts
- backend/src/database.ts
- backend/src/entity/Goods.ts
- backend/src/repository/category.repository.ts
- backend/src/repository/goods.repository.ts
- backend/src/router/category.router.ts
- backend/src/service/category.service.ts
- backend/src/service/goods.service.ts
- backend/src/types/response/category.response.ts
- frontend/admin/src/App.tsx
- frontend/admin/src/apis/categoryAPI.ts
- frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
- frontend/admin/src/pages/Main/Main.tsx
- frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategory/TopSellingCategory.tsx
- frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategoryList.tsx
- frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
- frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
- frontend/admin/src/theme/theme.ts
- frontend/admin/src/types/Category.ts
- frontend/client/src/components/GoodsItem/GoodsItem.tsx
- frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
대시보드 - Bar chart, Top Selling Category (컴포넌트 API 개발) , 제품 조회수 Column 추가 및 적용
https://user-images.githubusercontent.com/18898526/130542362-9a23323c-3d46-487c-8da9-b0cbef020183.mov
FE
BE
- 자식 카테고리를 다 가져오면 너무 광범위해질 것 같아 부모 카테고리로 view의 총합을 가져와서 비교를 했습니다!
> [feature/169] 대시보드 - Bar chart, Top Selling Category (컴포넌트 API 개발) , 제품 조회수 Column 추가 및 적용

- backend/src/repository/goods.repository.ts
- backend/src/repository/order.list.repository.ts
- backend/src/service/cart.service.ts
- backend/src/service/goods.service.ts
- backend/src/service/order.service.ts
- backend/src/types/request/order.request.ts
- frontend/client/src/apis/orderAPI.ts
- frontend/client/src/hooks/usePushToOrderPage.ts
- frontend/client/src/pages/Cart/CartPage.tsx
- frontend/client/src/pages/Order/OrderPage.tsx
- frontend/client/src/recoil/orderState.ts
https://user-images.githubusercontent.com/64543699/130441870-b5308fd3-12c0-4307-b846-a6da1cd0dd11.mov
- 타입과 백엔드 '로직 무결성' 위주로 봐주시면 좋을것 같습니다. 트랜잭션이 필요할까요?
> [feuatre/154] 장바구니 관련 비즈니스 로직 완성

- backend/src/database.ts
- backend/src/entity/DeliveryInfo.ts
- backend/src/entity/Order.ts
- frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTable.tsx
- frontend/admin/webpack.dev.js
- frontend/client/src/App.tsx
- frontend/client/src/components/Header/Header.tsx
- frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/IconContainerStyle.ts
- frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
- frontend/client/src/components/SideBar/RecentGoodsView.tsx
- frontend/client/src/components/SideBar/SideBar.tsx
- frontend/client/src/pages/Cart/CartPage.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInfo/InfoContent/InfoContent.tsx
- frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
- frontend/client/src/pages/Main/Main.tsx
- frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
최근 상품 조회 UI개선을 위한 작업을 진행했습니다.
그리고 Client App에서 수정할 만한 사소한 작업들을 진행했습니다.
- 이전 사이드드바 이미지
- 수정 후 사이드바 이미지
> [feature/186] 최근 상품 조회하는 사이드바 UI 수정 및 각종 사소한 Client UI/UX 수정 

- frontend/admin/src/components/Header/DashboardIcon/DashboardIcon.tsx
- frontend/admin/src/components/Header/GoodsAdminIcon/GoodsAdminIcon.tsx
- frontend/admin/src/components/Header/LogoIcon/LogoIcon.tsx
- frontend/admin/src/components/Header/OrderAdminIcon/OrderAdminIcon.tsx
- frontend/admin/src/components/Header/PromotionAdminIcon/PromotionAdminIcon.tsx
- frontend/admin/src/hooks/useInterval.ts
- frontend/admin/src/pages/GoodsAdmin/GoodsAdmin.tsx
- frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
- frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
- frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
- frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
- frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTable.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderRow.tsx
- frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableBody.tsx
- frontend/admin/src/pages/PromotionAdmin/PromotionAdmin.tsx
- frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
- frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionList.tsx
- frontend/admin/src/portal/ConfirmModal/ConfirmModal.tsx
- frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
- frontend/admin/src/portal/OrderModal/OrderCard.tsx
- frontend/admin/src/portal/OrderModal/OrderGoods.tsx
- frontend/admin/src/portal/OrderModal/OrderModal.tsx
- frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
- frontend/admin/webpack.dev.js
주문을 상세 조회하기 위해서 관리자페이지에서 주문 상세보기 모달을 추가했습니다. 그리고 관리자페이지지에서 모달들이 blur background를 클릭시 닫히도록 코드 수정을 진행했습니다.
> [feature/195] 주문 상세 보기 모달 추가 및 여러 모달 BlurBackground 클릭시 닫히도록 수정

- backend/src/service/category.service.ts
Category 조회 수 Goods가 부모 Category일 경우 예외 처리 
-[X] 카테고리 조회 수 가공할 때 부모 Category로만 등록된 Goods의 경우 예외처리
> [feature/197] Bug Category 조회 수 Goods가 부모 Category일 경우 예외 처리  

- frontend/client/src/lib/ToastProvider/ToastProvider.tsx
https://user-images.githubusercontent.com/64543699/130775854-e2b03318-6a13-4aa7-b997-b73410f546bc.mov
> [feature/209] Toast 기본 노출 시간 감소, 최대 노출 개수 로직 추가

- backend/src/controller/category.controller.ts
- backend/src/database.ts
- backend/src/entity/Category.ts
- backend/src/entity/Goods.ts
- backend/src/repository/category.repository.ts
- backend/src/router/category.router.ts
- backend/src/service/category.service.ts
- backend/src/types/response/category.response.ts
- frontend/admin/src/apis/categoryAPI.ts
- frontend/admin/src/pages/Main/CategoryPieChart/CategoryPieChart.tsx
제목 그대로 관리자페이지의 파이차트에서 정확한 상품 수를 출력하도록 수정했습니다.
진행하면서 Category Entitty에서 OneToMany 관계를 통해 Goods를 얻어와서 개수를 얻어내도록 수정했습니다.(코드 수정 최소화)
- Category Entity에 goodsList 라는 컬럼을 추가했습니다.
> [feature/214] 관리자페이지의 파이차트에서 정확한 상품 수를 출력하도록 수정했습니다.

- frontend/client/src/pages/Order/OrderPage.tsx
https://user-images.githubusercontent.com/64543699/131204274-25c197a4-0f8e-4e00-8533-d3ab5d6f4106.mov
간단한 리코일 상태 수정 코드를 추가했을 뿐입니다.
> [feature/250] 주문 완료 후 cart 상태 최신화

- backend/src/service/goods.service.ts
- frontend/client/src/pages/Main/Main.tsx
> fix: 메인 상품 리스트 버그 수정
